FROM node:20-alpine

WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем весь проект
COPY . .

# Собираем TypeScript
RUN npm run build

# Открываем порт
EXPOSE 5555

# Запускаем приложение
CMD ["npm", "start"]